### PR TITLE
WBTGEN-31502: Upgraded underscore & mocha to fix all critical vulnera…

### PR DESCRIPTION
**Pull request by suryakumar-ravi**
Upgraded underscore & mocha packages.
- All critical vulnerabilities have been fixed
- All tests were passing

### CODE REVIEW

**Comment by prashantrathi8579** [comment]
@papandreou Just added this commit. Need help to publish or please provide the permission to "https://www.npmjs.com/~prashantrathi"

**Comment by prashantrathi8579** [comment]
@papandreou Not able to publish. 
Can see following:
npm access list collaborators express-negotiator
gustavnikolaj: read-write
maartenwinter: read-write
moubi: read-write
papandreou: read-write

**Comment by papandreou** [comment]
When I added you it said:

```
$ npm owner add prashantrathi express-negotiator
npm notice INFO: User prashantrathi invited to package express-negotiator successfully.
+ prashantrathi (express-negotiator)
```

Maybe you need to accept the invite first?

**Comment by papandreou** [comment]
If that still doesn't work, maybe you can get Gustav to help?

**Pull request merged**
